// Root settings for the 78-app Android collection.
// Each numbered folder is mapped to a short Gradle module name so paths stay readable.
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "App-Collection"
include(":shared-ui")
include(":p01")
project(":p01").projectDir = file("01-gps-live-location")
include(":p02")
project(":p02").projectDir = file("02-flashlight")
include(":p03")
project(":p03").projectDir = file("03-sqlite-crud")
include(":p04")
project(":p04").projectDir = file("04-music-player")
include(":p05")
project(":p05").projectDir = file("05-webview-browser")
include(":p06")
project(":p06").projectDir = file("06-camera-launcher")
include(":p07")
project(":p07").projectDir = file("07-battery-monitor")
include(":p08")
project(":p08").projectDir = file("08-foreground-service")
include(":p09")
project(":p09").projectDir = file("09-notification-modern")
include(":p10")
project(":p10").projectDir = file("10-send-email")
include(":p11")
project(":p11").projectDir = file("11-share-content")
include(":p12")
project(":p12").projectDir = file("12-ringtone-picker")
include(":p13")
project(":p13").projectDir = file("13-date-picker")
include(":p14")
project(":p14").projectDir = file("14-countdown-timer")
include(":p15")
project(":p15").projectDir = file("15-date-time")
include(":p16")
project(":p16").projectDir = file("16-open-browser")
include(":p17")
project(":p17").projectDir = file("17-dialer")
include(":p18")
project(":p18").projectDir = file("18-image-gallery")
include(":p19")
project(":p19").projectDir = file("19-custom-list")
include(":p20")
project(":p20").projectDir = file("20-custom-font")
include(":p21")
project(":p21").projectDir = file("21-finger-paint")
include(":p22")
project(":p22").projectDir = file("22-image-animations")
include(":p23")
project(":p23").projectDir = file("23-chronometer")
include(":p24")
project(":p24").projectDir = file("24-rating-bar")
include(":p25")
project(":p25").projectDir = file("25-spinner-selector")
include(":p26")
project(":p26").projectDir = file("26-autocomplete")
include(":p27")
project(":p27").projectDir = file("27-multi-autocomplete")
include(":p28")
project(":p28").projectDir = file("28-simple-list")
include(":p29")
project(":p29").projectDir = file("29-grid-view")
include(":p30")
project(":p30").projectDir = file("30-radio-group")
include(":p31")
project(":p31").projectDir = file("31-checkbox")
include(":p32")
project(":p32").projectDir = file("32-toggle-button")
include(":p33")
project(":p33").projectDir = file("33-keyboard-input-types")
include(":p34")
project(":p34").projectDir = file("34-long-press-context")
include(":p35")
project(":p35").projectDir = file("35-html-text")
include(":p36")
project(":p36").projectDir = file("36-choice-dialog")
include(":p37")
project(":p37").projectDir = file("37-animated-dialog")
include(":p38")
project(":p38").projectDir = file("38-custom-toast")
include(":p39")
project(":p39").projectDir = file("39-form-validation")
include(":p40")
project(":p40").projectDir = file("40-array-adapter-list")
include(":p41")
project(":p41").projectDir = file("41-gps-ui-layout")
include(":p42")
project(":p42").projectDir = file("42-gps-permissions")
include(":p43")
project(":p43").projectDir = file("43-music-player-ui")
include(":p44")
project(":p44").projectDir = file("44-audio-manifest-modern")
include(":p45")
project(":p45").projectDir = file("45-webview-ui-layout")
include(":p46")
project(":p46").projectDir = file("46-webview-manifest-modern")
include(":p47")
project(":p47").projectDir = file("47-email-form-ui")
include(":p48")
project(":p48").projectDir = file("48-email-manifest")
include(":p49")
project(":p49").projectDir = file("49-notification-sound")
include(":p50")
project(":p50").projectDir = file("50-notification-ui")
include(":p51")
project(":p51").projectDir = file("51-notification-permission")
include(":p52")
project(":p52").projectDir = file("52-animated-dialog-ui")
include(":p53")
project(":p53").projectDir = file("53-dialog-dependency-migration")
include(":p54")
project(":p54").projectDir = file("54-form-ui-layout")
include(":p55")
project(":p55").projectDir = file("55-form-manifest")
include(":p56")
project(":p56").projectDir = file("56-custom-list-layout")
include(":p57")
project(":p57").projectDir = file("57-custom-list-row")
include(":p58")
project(":p58").projectDir = file("58-array-list-layout")
include(":p59")
project(":p59").projectDir = file("59-list-manifest")
include(":p60")
project(":p60").projectDir = file("60-listactivity-modern")
include(":p61")
project(":p61").projectDir = file("61-listactivity-manifest")
include(":p62")
project(":p62").projectDir = file("62-dialog-suite")
include(":p63")
project(":p63").projectDir = file("63-custom-dialog-one")
include(":p64")
project(":p64").projectDir = file("64-custom-dialog-layout")
include(":p65")
project(":p65").projectDir = file("65-custom-dialog-manifest")
include(":p66")
project(":p66").projectDir = file("66-custom-dialog-two")
include(":p67")
project(":p67").projectDir = file("67-custom-dialog-two-manifest")
include(":p68")
project(":p68").projectDir = file("68-toast-layout-migration")
include(":p69")
project(":p69").projectDir = file("69-toast-manifest")
include(":p70")
project(":p70").projectDir = file("70-flashlight-legacy-rewrite")
include(":p71")
project(":p71").projectDir = file("71-clock-modern")
include(":p72")
project(":p72").projectDir = file("72-clock-toolbox")
include(":p73")
project(":p73").projectDir = file("73-finger-paint-toolbox")
include(":p74")
project(":p74").projectDir = file("74-move-object-animation")
include(":p75")
project(":p75").projectDir = file("75-move-text-animation")
include(":p76")
project(":p76").projectDir = file("76-date-picker-toolbox")
include(":p77")
project(":p77").projectDir = file("77-send-email-toolbox")
include(":p78")
project(":p78").projectDir = file("78-progress-dialog-modern")
