specs = [
(1,'gps - Java.txt','gps-live-location','بازسازی ارزشمند','GPS و نمایش مختصات زنده','gps','افزودن نقشه آفلاین، ذخیره مسیر و اشتراک موقعیت'),
(2,'جعبه ابزار - چراغ قوه.txt','flashlight','بازسازی ارزشمند','چراغ قوه با CameraManager','flashlight','افزودن SOS، تنظیم شدت نور در دستگاه‌های پشتیبانی‌شده و ویجت'),
(3,'جعبه ابزار - دیتابیس - همه کارها.txt','sqlite-crud','بازسازی ارزشمند','مدیریت داده محلی SQLite با CRUD','sqlite','مهاجرت اختیاری به Room، جستجو، خروجی CSV و پشتیبان‌گیری'),
(4,'music player - java.txt','music-player','بازسازی ارزشمند','پخش صوت و کنترل Play/Pause','music','افزودن پلی‌لیست، MediaSession، پخش پس‌زمینه و اکولایزر'),
(5,'webview - java.txt','webview-browser','بازسازی ارزشمند','مرورگر داخلی WebView','webview','افزودن تب‌ها، تاریخچه، دانلود و Safe Browsing'),
(6,'جعبه ابزار - دوربین.txt','camera-launcher','بازسازی ارزشمند','باز کردن دوربین و ثبت تصویر','camera','افزودن CameraX، گالری داخلی، برش و فشرده‌سازی تصویر'),
(7,'جعبه ابزار - نمایش شارژ باتری.txt','battery-monitor','بازسازی ارزشمند','نمایش درصد و وضعیت باتری','battery','افزودن نمودار مصرف، هشدار شارژ و تاریخچه'),
(8,'backgrounds service.txt','foreground-service','بازسازی ارزشمند','سرویس پس‌زمینه مدرن','service','افزودن WorkManager برای کارهای زمان‌بندی‌شده و کنترل اعلان'),
(9,'جعبه ابزار - نوتفیگیشن.txt','notification-modern','بازسازی ارزشمند','اعلان استاندارد با NotificationChannel','notification','افزودن اکشن، دسته‌بندی، زمان‌بندی و اعلان گروهی'),
(10,'send mail - java.txt','send-email','بازسازی ارزشمند','ارسال ایمیل با Intent','email','افزودن قالب پیام، پیوست و اعتبارسنجی آدرس'),
(11,'جعبه ابزار - به اشتراک گذاری.txt','share-content','بازسازی ارزشمند','اشتراک متن با Android Sharesheet','share','افزودن اشتراک فایل، تصویر و لینک هوشمند'),
(12,'جعبه ابزار - انتخاب صدای زنگ.txt','ringtone-picker','بازسازی ارزشمند','انتخاب صدای زنگ سیستم','ringtone','افزودن پیش‌نمایش صدا و ذخیره انتخاب'),
(13,'dialog date picker.txt','date-picker','بازسازی ارزشمند','انتخاب تاریخ با DatePickerDialog','date','افزودن تاریخ شمسی، اختلاف تاریخ و یادآور'),
(14,'جعبه ابزار - شمارنده معکوس.txt','countdown-timer','بازسازی ارزشمند','شمارنده معکوس','countdown','افزودن چند تایمر، اعلان پایان و preset'),
(15,'currentDateTime.txt','date-time','بازسازی ارزشمند','نمایش تاریخ و ساعت جاری','datetime','افزودن منطقه زمانی، شمسی و تبدیل تاریخ'),
(16,'browser.txt','open-browser','بازسازی ارزشمند','باز کردن لینک در مرورگر امن','browser','افزودن اعتبارسنجی URL و Custom Tabs'),
(17,'dailpad.txt','dialer','بازسازی ارزشمند','باز کردن شماره‌گیر با شماره','dialer','افزودن دفترچه تماس و تاریخچه شماره‌ها'),
(18,'project gallery view.txt','image-gallery','بازسازی ارزشمند','گالری افقی تصاویر جایگزین Gallery منسوخ','gallery','افزودن انتخاب چندگانه، زوم و اسلایدشو'),
(19,'listView - custom - java.txt','custom-list','بازسازی ارزشمند','لیست سفارشی متن و تصویر','customlist','مهاجرت به RecyclerView/Compose و فیلتر'),
(20,'set custom font.txt','custom-font','بازسازی ارزشمند','نمایش Typeface و فونت سفارشی','font','افزودن انتخاب فونت و تنظیم اندازه/وزن'),
(21,'paint.txt','finger-paint','بازسازی ارزشمند','نقاشی با لمس روی Canvas','paint','افزودن رنگ، پاک‌کن، Undo/Redo و ذخیره PNG'),
(22,'جعبه ابزار - انیمیشن های روی عکس.txt','image-animations','بازسازی ارزشمند','انیمیشن Alpha/Rotate/Scale/Translate','animation','افزودن MotionLayout یا Compose Animation'),
(23,'chornometr.txt','chronometer','بازسازی ارزشمند','کرنومتر Start/Stop/Reset','chronometer','افزودن Lap، ذخیره رکوردها و ویجت'),
(24,'RatingStar.txt','rating-bar','بازسازی ارزشمند','امتیازدهی ستاره‌ای','rating','افزودن متن بازخورد و ذخیره امتیاز'),
(25,'Spinner.txt','spinner-selector','کد آموزشی مفید','انتخاب گزینه با Spinner','spinner','افزودن جستجو و Dropdown سفارشی'),
(26,'autoCompletCode.txt','autocomplete','کد آموزشی مفید','AutoCompleteTextView','autocomplete','اتصال به داده پویا و debounce جستجو'),
(27,'autoCompletCodeMulti.txt','multi-autocomplete','کد آموزشی مفید','MultiAutoCompleteTextView','multiautocomplete','تگ‌های قابل حذف و پیشنهاد از دیتابیس'),
(28,'list view.txt','simple-list','کد آموزشی مفید','لیست ساده قابل کلیک','list','مهاجرت به RecyclerView یا LazyColumn'),
(29,'gridview1.txt','grid-view','کد آموزشی مفید','نمایش GridView','grid','مهاجرت به RecyclerView GridLayoutManager یا Compose'),
(30,'RadioGroup.txt','radio-group','کد آموزشی مفید','RadioGroup و انتخاب یکتا','radio','ذخیره انتخاب و فرم چندمرحله‌ای'),
(31,'checkBox.txt','checkbox','کد آموزشی مفید','CheckBox و انتخاب چندگانه','checkbox','ذخیره state و گروه‌بندی گزینه‌ها'),
(32,'togleBotton.txt','toggle-button','کد آموزشی مفید','ToggleButton روشن/خاموش','toggle','جایگزینی با SwitchMaterial و ذخیره تنظیمات'),
(33,'جعبه ابزار - تغییر صفحه کیبورد.txt','keyboard-input-types','کد آموزشی مفید','نوع ورودی کیبورد برای Email/Password/Number','keyboard','اعتبارسنجی فرم و نمایش/مخفی کردن رمز'),
(34,'جعبه ابزار - تغیر رنگ متن با فشار طولانی.txt','long-press-context','کد آموزشی مفید','Long Press و Context Action','longpress','Contextual ActionMode و منوی سفارشی'),
(35,'htlmcode.txt','html-text','کد آموزشی مفید','رندر HTML ساده در TextView','html','پشتیبانی لینک قابل کلیک و sanitization'),
(36,'جعبه ابزار - دیالوگ.txt','choice-dialog','بازسازی ارزشمند','دیالوگ انتخاب تک‌گزینه‌ای','dialog','افزودن MultiChoice و DialogFragment'),
(37,'dialog - custom - material - java.txt','animated-dialog','بازسازی ارزشمند','دیالوگ انیمیشنی بدون کتابخانه قدیمی','animateddialog','افزودن انیمیشن‌های قابل انتخاب و تم پویا'),
(38,'toast - custom - java.txt','custom-toast','کد آموزشی مفید','پیام Toast مدرن','toast','جایگزینی UX با Snackbar در نسخه AndroidX'),
(39,'save data send string - java.txt','form-validation','بازسازی ارزشمند','فرم نام و تلفن با اعتبارسنجی','form','ذخیره محلی، ماسک شماره و فرم چندمرحله‌ای'),
(40,'listview - array adapter - java.txt','array-adapter-list','کد آموزشی مفید','ArrayAdapter و ListView','list','مهاجرت به RecyclerView و DiffUtil'),
(41,'gps - xml.txt','gps-ui-layout','کد آموزشی مفید','بازسازی رابط GPS قدیمی به UI برنامه‌نویسی‌شده','gpsui','اضافه کردن کارت مختصات، دقت و ارتفاع'),
(42,'gps - manifest.txt','gps-permissions','کد آموزشی مفید','آموزش مجوزهای Location مدرن','gpsperm','مجوز approximate/precise و background location'),
(43,'music player - xml.txt','music-player-ui','کد آموزشی مفید','رابط کنترل پخش موسیقی','musicui','SeekBar، زمان، کاور و کنترل gesture'),
(44,'music player - manifest.txt','audio-manifest-modern','کد آموزشی مفید','آموزش تنظیمات Manifest برای پخش صوت','audiomanifest','Foreground media service و MediaSession'),
(45,'webview - xml.txt','webview-ui-layout','کد آموزشی مفید','رابط WebView با نوار آدرس','webviewui','نوار پیشرفت، Back/Forward و تب'),
(46,'webview - manifest.txt','webview-manifest-modern','کد آموزشی مفید','آموزش مجوز و Manifest وب','webviewmanifest','Network Security Config و HTTPS-only'),
(47,'send mail - xml.txt','email-form-ui','کد آموزشی مفید','فرم گیرنده/موضوع/متن ایمیل','emailui','پیوست و autocomplete مخاطب'),
(48,'send mail - manifest.txt','email-manifest','کد آموزشی مفید','آموزش Intent و Manifest ایمیل','emailmanifest','استفاده از package visibility برای کلاینت ایمیل'),
(49,'notfigation - java.txt','notification-sound','تکراری / منسوخ بازسازی‌شده','Notification قدیمی با صدا، بازنویسی با Channel','notification','افزودن صدای سفارشی و اکشن'),
(50,'notfigation - xml.txt','notification-ui','کد آموزشی مفید','رابط ساخت اعلان','notificationui','فرم عنوان/متن، اهمیت و preview'),
(51,'notfigation - manifest.txt','notification-permission','تکراری / منسوخ بازسازی‌شده','مجوز اعلان Android 13+','notificationperm','مدیریت وضعیت مجوز و صفحه تنظیمات سیستم'),
(52,'dialog - custom - material - xml.txt','animated-dialog-ui','تکراری / منسوخ بازسازی‌شده','رابط دیالوگ متریال قدیمی، بازسازی با Dialog استاندارد','animateddialogui','تم پویا و گوشه گرد'),
(53,'dialog - custom - material - gradle.txt','dialog-dependency-migration','تکراری / منسوخ بازسازی‌شده','جایگزینی dependency قدیمی NiftyDialog','migration','نمایش راهنمای مهاجرت و نمونه داخلی بدون dependency'),
(54,'save data send string - xml.txt','form-ui-layout','کد آموزشی مفید','رابط فرم نام و تلفن','formui','TextInputLayout در نسخه AndroidX'),
(55,'save data send string - manifest.txt','form-manifest','کد آموزشی مفید','Manifest نمونه فرم','manifestdemo','آموزش exported و intent-filter مدرن'),
(56,'listView - custom - xml.txt','custom-list-layout','کد آموزشی مفید','Layout لیست سفارشی','customlistui','CardView/RecyclerView یا Compose Card'),
(57,'listView - custom - extra.txt','custom-list-row','کد آموزشی مفید','ردیف سفارشی لیست','customrow','ViewHolder بهینه و تصاویر async'),
(58,'listview - array adapter - xml.txt','array-list-layout','کد آموزشی مفید','Layout لیست ArrayAdapter','listui','RecyclerView و empty state'),
(59,'listview - array adapter - manifest.txt','list-manifest','کد آموزشی مفید','Manifest نمونه ListView','manifestdemo','تم و exported مدرن'),
(60,'listAcrivity - array adapter - java.txt','listactivity-modern','تکراری / منسوخ بازسازی‌شده','جایگزینی ListActivity منسوخ با Activity + ListView','list','مهاجرت کامل به RecyclerView'),
(61,'listAcrivity - array adapter - manifest.txt','listactivity-manifest','تکراری / منسوخ بازسازی‌شده','Manifest ListActivity قدیمی، بازسازی استاندارد','manifestdemo','Deep link و adaptive icon'),
(62,'dialog - custom - 1.txt','dialog-suite','بازسازی ارزشمند','مجموعه AlertDialog و Custom Dialog','dialogsuite','BottomSheet و DialogFragment'),
(63,'dialog - custom1 - java.txt','custom-dialog-one','تکراری / منسوخ بازسازی‌شده','Custom Dialog نسخه ۱','dialog','افزودن validation و state restoration'),
(64,'dialog - custom1 - xnl.txt','custom-dialog-layout','تکراری / منسوخ بازسازی‌شده','XML دیالوگ با نام فایل اشتباه، بازسازی UI','dialogui','Layout responsive و accessibility'),
(65,'dialog - custom1 -manifest.txt','custom-dialog-manifest','تکراری / منسوخ بازسازی‌شده','Manifest دیالوگ نسخه ۱','manifestdemo','تم dialog activity و exported امن'),
(66,'dialog - custom2 - java.txt','custom-dialog-two','تکراری / منسوخ بازسازی‌شده','Custom Dialog نسخه ۲','dialog','افزودن callback و ViewModel در نسخه پیشرفته'),
(67,'dialog - custom2 - manifest.txt','custom-dialog-two-manifest','تکراری / منسوخ بازسازی‌شده','Manifest دیالوگ نسخه ۲','manifestdemo','تم و lifecycle مدرن'),
(68,'toast - custom - xml.txt','toast-layout-migration','تکراری / منسوخ بازسازی‌شده','Layout Toast سفارشی قدیمی','toast','Snackbar یا in-app banner'),
(69,'toast - custom - manifest.txt','toast-manifest','تکراری / منسوخ بازسازی‌شده','Manifest Toast قدیمی','manifestdemo','کاهش اجزای غیرضروری Manifest'),
(70,'flash.txt','flashlight-legacy-rewrite','تکراری / منسوخ بازسازی‌شده','نسخه تکراری چراغ قوه با API جدید','flashlight','افزودن استروب و SOS'),
(71,'clock.txt','clock-modern','تکراری / منسوخ بازسازی‌شده','ساعت دیجیتال/آنالوگ قدیمی، بازسازی','clock','تایمر، آلارم و مناطق زمانی'),
(72,'جعبه ابزار - ساعت دیجیتال و آنالوگ.txt','clock-toolbox','تکراری / منسوخ بازسازی‌شده','نسخه فارسی همان ساعت، بازسازی مستقل','clock','پوسته‌های ساعت و ویجت'),
(73,'جعبه ابزار - نقاشی.txt','finger-paint-toolbox','تکراری / منسوخ بازسازی‌شده','نسخه فارسی نقاشی، بازسازی مستقل','paint','لایه‌ها، اشکال و خروجی تصویر'),
(74,'move object in screen.txt','move-object-animation','تکراری / منسوخ بازسازی‌شده','TranslateAnimation قدیمی، بازنویسی با ViewPropertyAnimator','move','physics animation و gesture'),
(75,'جابجایی متن در تصویر.txt','move-text-animation','تکراری / منسوخ بازسازی‌شده','نسخه فارسی حرکت متن، بازسازی مستقل','move','مسیر حرکت و سرعت قابل تنظیم'),
(76,'جعبه ابزار - تاریخ.txt','date-picker-toolbox','تکراری / منسوخ بازسازی‌شده','نسخه تکراری DatePicker، بازسازی','date','تاریخ شمسی و بازه تاریخ'),
(77,'جعبه ابزار - ازسال ایمیل.txt','send-email-toolbox','تکراری / منسوخ بازسازی‌شده','نسخه فارسی و تکراری ارسال ایمیل، بازسازی با Intent مدرن','email','افزودن قالب پیام، پیوست و مخاطبان اخیر'),
(78,'جعبه ابزار - لکدینگ پروگرس تایمر.txt','progress-dialog-modern','تکراری / منسوخ بازسازی‌شده','ProgressDialog منسوخ، بازسازی با ProgressBar داخل Dialog','progress','افزودن لغو عملیات، درصد واقعی و WorkManager'),
]

assert len(specs) == 78, len(specs)
originals = [s[1] for s in specs]
